// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4eenZ0mbzbPcfYHzFd9UzOU9z_R4owkc',
    appId: '1:76798830675:web:190f5973d88ca12d94bea6',
    messagingSenderId: '76798830675',
    projectId: 'blood-a5a26',
    authDomain: 'blood-a5a26.firebaseapp.com',
    storageBucket: 'blood-a5a26.appspot.com',
    measurementId: 'G-2HDG0L9NPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVerSVFbbyKWMAeZjXLLslo-mcGkdBOq4',
    appId: '1:76798830675:android:eecc0f689ee5220394bea6',
    messagingSenderId: '76798830675',
    projectId: 'blood-a5a26',
    storageBucket: 'blood-a5a26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfEasn5lnPlaI9vGKx64EcSSGjXSI4OS4',
    appId: '1:76798830675:ios:1d5ad0ba93c254e794bea6',
    messagingSenderId: '76798830675',
    projectId: 'blood-a5a26',
    storageBucket: 'blood-a5a26.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfEasn5lnPlaI9vGKx64EcSSGjXSI4OS4',
    appId: '1:76798830675:ios:1d5ad0ba93c254e794bea6',
    messagingSenderId: '76798830675',
    projectId: 'blood-a5a26',
    storageBucket: 'blood-a5a26.appspot.com',
    iosBundleId: 'com.example.blood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4eenZ0mbzbPcfYHzFd9UzOU9z_R4owkc',
    appId: '1:76798830675:web:4342ce398f4aae6a94bea6',
    messagingSenderId: '76798830675',
    projectId: 'blood-a5a26',
    authDomain: 'blood-a5a26.firebaseapp.com',
    storageBucket: 'blood-a5a26.appspot.com',
    measurementId: 'G-ZD78YED8YM',
  );
}
